version: "3.0"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: "advertisement_crud"
      MYSQL_PASSWORD: "QEU2zYILBoMAH26Q"
      MYSQL_DATABASE: "advertisement_crud"
      MYSQL_ROOT_PASSWORD: "pass"

  server:
    build: .
    working_dir: /go/src/advertisement_crud
    volumes:
      - .:/go/src/advertisement_crud
      - /go/src/advertisement_crud/docs  # excluded, being generated on build and should not be replaced
      - /go/src/advertisement_crud/mocks # excluded, being generated on build and should not be replaced
      - ./etc/config/config.json:/etc/advertisement_crud/config.json
    depends_on:
      - db
    ports:
      - 24112:24112
    command: go run main.go