package main

import (
	"advertisement_crud/application"
	"advertisement_crud/controller"
	"advertisement_crud/etc/config"
	"advertisement_crud/model"

	_ "advertisement_crud/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Advertisement API
// @description TODO: Grooming validation errors view
// @description TODO: refactor migrations flow
// @description TODO: prevent races between containers on first start
// @description TODO: support russian language in advertisements
// @description
// @contact.name Stepan Morozov
// @contact.email stepan.morozov.work@gmail.com
func main() {
	conf := config.New("/etc/advertisement_crud/config.json")
	m := model.New(conf.Database)
	if !m.IsMigrated() {
		m.Migrate()
	}

	a := application.New(m)
	c := controller.New(a, conf)

	c.ServeHTTP()
}
